[build]
  
  command = "npm install && npm run build" # adjust this command based on your project setup
  publish = "dist" # adjust this directory based on your project setup

[dev]
  command = "npm run start" # adjust this command based on your project setup